// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnE46HhChKV9eyKCq0XngqAXHKsPE6yrA',
    appId: '1:642198949669:web:f4f15d7d13fb5c02a6d4cc',
    messagingSenderId: '642198949669',
    projectId: 'moodify-c632b',
    authDomain: 'moodify-c632b.firebaseapp.com',
    storageBucket: 'moodify-c632b.firebasestorage.app',
    measurementId: 'G-EWZ59WQD5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6eOUDlvajW4uZdtRLsCYsteMRqXSoB20',
    appId: '1:642198949669:android:cd14a602ab319486a6d4cc',
    messagingSenderId: '642198949669',
    projectId: 'moodify-c632b',
    storageBucket: 'moodify-c632b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkFB1xpuabJq0wG75wGqR0twTNdInd_A8',
    appId: '1:642198949669:ios:6d207ec9171edd07a6d4cc',
    messagingSenderId: '642198949669',
    projectId: 'moodify-c632b',
    storageBucket: 'moodify-c632b.firebasestorage.app',
    iosClientId: '642198949669-79m1ro6k1mmdbmpia0sso6jr3545ejub.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkFB1xpuabJq0wG75wGqR0twTNdInd_A8',
    appId: '1:642198949669:ios:6d207ec9171edd07a6d4cc',
    messagingSenderId: '642198949669',
    projectId: 'moodify-c632b',
    storageBucket: 'moodify-c632b.firebasestorage.app',
    iosClientId: '642198949669-79m1ro6k1mmdbmpia0sso6jr3545ejub.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnE46HhChKV9eyKCq0XngqAXHKsPE6yrA',
    appId: '1:642198949669:web:0b3c744ee3aaea69a6d4cc',
    messagingSenderId: '642198949669',
    projectId: 'moodify-c632b',
    authDomain: 'moodify-c632b.firebaseapp.com',
    storageBucket: 'moodify-c632b.firebasestorage.app',
    measurementId: 'G-NERKK0TCRT',
  );
}
